/*
 * Trainingsdaten
 * Hier können Wurfgruppen, Würfe und Situationsvorgaben einfach erweitert werden.
 */

const THROW_DATA = {
  groups: {
    basic: {
      name: "Kyu",
      throws: [
        "(Morote-)Seoi-nage",        
        "O-goshi",
        "Uki-goshi",
        "O-uchi-gari",
        "Ippon-seoi-nage",
        "Koshi-guruma",
        "Sode-tsurikomi-goshi",
        "Ko-uchi-gari",
        "Tai-otoshi",
        "Tsurikomi-goshi",
        "Sasae-tsurikomi-ashi",
        "Ko-soto-gari (-gake)",
        "Uchi-mata",
        "Harai-goshi",
        "O-soto-gari (-otoshi)",
        "De-ashi-barai",
        "Tani-otoshi",
        "(Yoko-) Tomoe-nage",
        "Okuri-ashi-barai",
        "Tsuri-Goshi",
        "Soto-makikomi",
        "(Yoko-) Sumi-gaeshi",
        "Ashi-Guruma",
        "Kata-Guruma",
        "Ura-nage",
        "Ko-uchi-makikomi",
        "Uki-otoshi",
        "Utsuri-goshi"       
      ]
    },

    extension: {
      name: "1.DAN",
      throws: [
        "(Morote-)Seoi-nage",        
        "O-goshi",
        "Uki-goshi",
        "O-uchi-gari",
        "Ippon-seoi-nage",
        "Koshi-guruma",
        "Sode-tsurikomi-goshi",
        "Ko-uchi-gari",
        "Tai-otoshi",
        "Tsurikomi-goshi",
        "Sasae-tsurikomi-ashi",
        "Ko-soto-gari",
        "Uchi-mata",
        "Harai-goshi",
        "O-soto-gari (-otoshi)",
        "De-ashi-barai",
        "Tani-otoshi",
        "(Yoko-) Tomoe-nage",
        "Okuri-ashi-barai",
        "Tsuri-Goshi",
        "Soto-makikomi",
        "(Yoko-) Sumi-gaeshi",
        "Ashi-Guruma",
        "Kata-Guruma",
        "Ura-nage",
        "Ko-uchi-makikomi",
        "Uki-otoshi",
        "Utsuri-goshi",
        "Sukui-nage",
        "Sumi-otoshi",
        "Hane-goshi",
        "Ushiro-goshi",
        "Hiza-guruma",
        "Ko-soto-gake",
        "Harai-tsurikomi-ashi",
        "O-guruma",
        "O-soto-guruma",
        "Yoko-otoshi",
        "Hane-makikomi",
        "Uki-waza",
        "Yoko-wakare",
        "Yoko-guruma",
        "Yoko-gake"
      ]
    },

    all: {
      name: "All Kodokan throws",
      throws: [
        "Seoi-nage",
        "Ippon-seoi-nage",
        "Seoi-otoshi",
        "Tai-otoshi",
        "Kata-guruma",
        "Sukui-nage",
        "Obi-otoshi",
        "Uki-otoshi",
        "Sumi-otoshi",
        "Yama-arashi",
        "Obi-tori-gaeshi",
        "Morote-gari",
        "Kuchiki-taoshi",
        "Kibisu-gaeshi",
        "Uchi-mata-sukashi",
        "Ko-uchi-gaeshi",
        "Uki-goshi",
        "O-goshi",
        "Koshi-guruma",
        "Tsurikomi-goshi",
        "Sode-tsurikomi-goshi",
        "Harai-goshi",
        "Tsuri-goshi",
        "Hane-goshi",
        "Utsuri-goshi",
        "Ushiro-goshi",
        "De-ashi-harai",
        "Hiza-guruma",
        "Sasae-tsurikomi-ashi",
        "O-soto-gari",
        "O-uchi-gari",
        "Ko-soto-gari",
        "Ko-uchi-gari",
        "Okuri-ashi-harai",
        "Uchi-mata",
        "Ko-soto-gake",
        "Ashi-guruma",
        "Harai-tsurikomi-ashi",
        "O-guruma",
        "O-soto-guruma",
        "O-soto-otoshi",
        "Tsubame-gaeshi",
        "O-soto-gaeshi",
        "O-uchi-gaeshi",
        "Hane-goshi-gaeshi",
        "Harai-goshi-gaeshi",
        "Uchi-mata-gaeshi",
        "Tomoe-nage",
        "Sumi-gaeshi",
        "Hikikomi-gaeshi",
        "Tawara-gaeshi",
        "Ura-nage",
        "Yoko-otoshi",
        "Tani-otoshi",
        "Hane-makikomi",
        "Soto-makikomi",
        "Uchi-makikomi",
        "Uki-waza",
        "Yoko-wakare",
        "Yoko-guruma",
        "Yoko-gake",
        "Daki-wakare",
        "O-soto-makikomi",
        "Uchi-mata-makikomi",
        "Harai-makikomi",
        "Ko-uchi-makikomi",
        "Kani-basami",
        "Kawazu-gake"
      ]
    }

  },

  situations: [
    "Kombination",
    "Finte",
    "Konter",
    "Seitenwechsel"
  ]
};

/*

      */